# Generated by Django 5.1.2 on 2024-10-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraperlog',
            name='log',
        ),
        migrations.AddField(
            model_name='scraperlog',
            name='log_file_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
